Titles = {
    "alerts":{
        "teaTypes":["Tea types information is not loaded correctly!","Les informations sur les types de thé ne sont pas chargées correctement!"], 
        "teaModels":["Tea models information is not loaded correctly!","Les informations sur les models de thé ne sont pas chargées correctement!"], 
        "informationLoad":["The information is not loaded correctly, Refresh the page please!","Les informations ne sont pas chargées correctement, Actualisez la page s'il vous plaît!"], 
        "userNotFound":["Username or password are not found!","Nom d'utilisateur ou mot de passe ne sont pas trouvés!"], 
        "passwordNotMatch":["Passwords are not match!","Les mots de passe ne correspondent pas!"], 
        "emailExists":["This emial(user) already exists!","Cet email (utilisateur) existe déjà!"], 
        "errorSendEmail":["An error occurred while sending message!","Une erreur est survenue lors de l'envoi du message!"], 
        "errorSaveData":["An error occurred while save data!","Une erreur est survenue lors de la sauvegarde des données!"], 
    },
    "header":{
        "languages": ["FR", "EN"],
        "subscribe":["Subscribe","Souscrire"],
        "login":["Login","Connection"],
        "registerNow":["Register now","Inscrire maintenant"],
        "username":["Username","Nom d\'utilisateur"],
        "password":["Password","Mot de passe"],
        "logout":["Log out","Déconnecter"],
        "hi":["Hi","Salut"]
    },
    "specialLinks":{
        "flowers": ["Flowers","Fleurs"],
        "teaShop":["Tea shop","Boutique de thé"]
    },
    "footer":{
        "supportCenter":["Support center","Service clientèle"],
        "termOfUse":["Term of use","Conditions d\'utilisation"],
        "contactUs":["Contact us","Contactez nous"],
        "myAccount":["My account","Mon compte"],
        "faq":["FAQ","Questions fréquentes"],
        "copyRight":["All right reserved, GreenPortal 2018","Tous droits réservés, GreenPortal 2018"]
    },
    "rightBox":{
        "shopBy":["- Shop by -","- Acheter par -"],
        "type":["type","type"],
        "slogan":["SAFE, FAST and RELIABLE","SÛR, RAPIDE et FIABLE"],
        "subscribe":["Subscribe","Souscrire"],
    },
    "section2":{
        "freeShipping":["free shipping","livraison gratuite"],
        "onOrderOver":["on order over 100$","sur commande de plus de 100 $"],
        "fast":["fast and efficient","rapide et efficace"],
        "quality":["quality products delivered","produits de qualité livrés"],
        "tracking":["tracking number provided","numéro de suivi fourni"],
        "teaXpress":["Tea Xpress-POST","Tea Xpress-POST"],
    },
    "section3":{
        "teaShop":["Tea shop","Boutique de thé"]
    },
    "section4":{
        "howCanHelp":["How can we help?","Comment pouvons nous aider?"],
        "dropALine":["Drop us a line","Laissez-nous une ligne"],
        "hoursOperation":["Hours of operation","Heures d\'ouverture"],
        "workingDays":["Monday - Friday : 11 am - 5 pm","lundi - vendredi: 11h à 17h"],
        "holidays1":["Saturday - Sunday : Closed","Samedi - Dimanche: fermé"],
        "holidays2":["Statutory holidays : closed","Jours fériés: fermé"],
        "send":["send","envoyer"]
    },
    "section1Ad":{
        "orders":["Orders","Commandes"], 
        "userProfiles":["user profiles","des profils d'utilisateurs"],
        "orderDate":["order date","date de commande"], 
        "customerName":["Customer name","Nom du client"], 
        "total":["Total","Total"], 
        "moneyReceived":["money received","argent reçu"], 
        "orderSent":["order sent","commande envoyée"], 
        "all":["All","Tout"], 
        "address":["address","adresse"], 
        "title":["Title","Titre"], 
        "qty":["Qty","Qté"], 
        "weight":["weight","poids"], 
        "tax":["tax","tax"], 
        "postCost":["Post cost","Frais postaux"], 
        "credit":["credit","crédit"], 
        "payable":["payable","payable"], 
        "save":["save","sauvegarder"], 
        "delete":["delete","effacer"], 
        "deletePending":["Clean the list...","Nettoyer la liste..."], 
        "deletePending3days":["Delete the pending commands more than 3 days","Supprimer les commandes en attente plus de 3 jours"], 
        "phoneNo":["phone number","numéro de téléphone"], 
        "special":["special","spécial"], 
        "active":["active","active"], 
        "name":["Name","Prénom"], 
        "lastName":["Last name","Nom de famille"], 
        "email":["Email","Email"], 
        "ableLogin":["Able to login","Capable de se connecter"], 
        "seeSpecial":["Able to see the special products","Capable de voir les produits spéciaux"],
        "customerInfo":["Client information","Informations client"],
        "price":["Price","Prix"],
        "prCity":["Province/City","Province/Ville"],
        "pCode":["p.code","c.postale"],
        "city":["city","ville"], 
        "province":["province","province"], 
        "messages":["Messages","Messages"], 
        "message":["Message","Message"], 
        "trackNo":["Tracking no.","No. de suivi"], 
        "deletePendingConfirmText":["Pending purchases for more than 3 days will be deleted permanently. Are you sure?","Les achats en attente de plus de 3 jours seront définitivement supprimés. Êtes-vous sûr?"] 
    },
    "section2s":{
        "products":["products","produits"], 
        "text1":["It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        "On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français standard. De nombreuses suites logicielles de mise en page ou éditeurs de sites Web ont fait du Lorem Ipsum leur faux texte par défaut, et une recherche pour 'Lorem Ipsum' vous conduira vers de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter de petits clins d'oeil, voire des phrases embarassantes)."]
    },
    "index":{
        "subscribe":["Subscribe","Souscrire"],
        "username":["Username","Nom d\'utilisateur"],
        "password":["Password","Mot de passe"], 
        "name":["Name","Prénom"],
        "lastname":["Last name","Nom de famille"], 
        "email":["Email","Email"],
        "send":["send","envoyer"], 
        "grade":["Grade","Qualité"], 
        "selectQty":["Select quantity","Sélectionnez la quantité"],
        "addToBasket":["Add to basket","Ajouter au panier"], 
        "title":["Title","Titre"], 
        "qty":["Qty","Qté"], 
        "price":["Price","Prix"], 
        "total":["Total","Total"], 
        "confirm":["Confirm","Confirmer"], 
        "products":["products","produits"], 
        "passwordConfirm":["Password confirmation","Confirmation mot de passe"], 
        "address":["address","adresse"],
        "phoneNo":["phone number","numéro de téléphone"], 
        "back":["back","retour"], 
        "credit":["credit","crédit"], 
        "login":["Login","Connection"], 
        "postCost":["Post cost","Frais postaux"], 
        "payable":["payable","payable"], 
        "purchaseDate":["purchase date","date d'achat"], 
        "payed":["Payed","payé"], 
        "save":["save","sauvegarder"],
        "client":["client","client"], 
        "tax":["tax","tax"], 
        "pendingPurchase":["pending purchases","achats en attente"],
        "pCode":["p.code","c.postale"],
        "city":["city","ville"], 
        "province":["province","province"], 
        "purchases":["purchases","achats"],
        "toFinishPurchase1":["To finish your purchase please pay","Pour terminer votre achat, veuillez payer"], 
        "toFinishPurchase2":["by Interac to email address info.greenportal@gmail.com within 2 days.","par Interac à l’adresse courriel info.greenportal@gmail.com dans 2 jours."],
        "membership":["membership","adhésion"],
        "iHave19":["I have 19+ years old","J'ai 19+ ans"],
        "iAmCitizen":["I am citizen of Canada","Je suis citoyen du Canada"], 
        "condition3": ["This ID confirm the information below", "Cet identifiant confirme les informations ci-dessous"],
        "proceed":["proceed","procéder"],
        "previous":["previous","precedent"],
        "profile":["profile","profil"],
        "uploadMsg":["Identification documents","Documents d'identification"],
        "photoMsg": ["Take a photo of a valid government ID (such as a passport or driver’s license)", "Prenez une photo d'une pièce d'identité gouvernementale valide (comme un passeport ou un permis de conduire)"],
        "photoReceived": ["Thank you, an identity verification will be done by Greenportal.ca", "Merci, une vérification d'identité sera faite par Greenportal.ca"],
        "forgotPassword": ["Forgot password?", "Mot de passe oublié?"],
        "fp_msg": ["To retrieve your Password, please enter your email address (user name).","Afin de récupérer votre Mot de passe, veuillez saisir votre adresse de courriel (Nom d\'utilisateur)."],
        "youAreConfirmed": ["you are now member of greenportal.ca", "Vous êtes maintenant membre de greenportal.ca"]
    },
    "purchase":{
        "clietInfoTitle":["Client's information","Informations du client"],
        "fullName":["Full name","Nom complet"], 
        "lastName":["Last name","Nom de famille"], 
        "adress":["Address","Adresse"],
        "phoneNo":["Phone number","Numéro de téléphone"], 
        "howPay":["How to pay?","Comment payer?"], 
        "orderNo": ["Order number", "No. de commande"],
        "payment":["Payment","Payment"], 
        "howPayText1":["Please pay the payable amount","Veuillez payer le montant à payer"], 
        "howPayText2":["by interac within 3 days to email address","par Interac dans 3 jours à l'adresse électronique"], 
        "howPayText3":["We keep this purchase in pending list for 3 days, in case of non-complete purchases, we will remove them from the list.","Nous conservons cet achat dans la liste d'attente pendant 3 jours. En cas d'achats non complets, nous les retirerons de la liste."], 
        "adressIncomplete":["The address is incomplete or is not correct, please edit your address in your profile.","L'adresse est incomplète ou n'est pas correcte, Veuillez modifier votre adresse dans votre profil."], 
    },
    "productModal":{
        "effects":["Effects", "Effets"],
        "medical":["Medical","Médicale"],
        "negatives":["Negatives","Les Négatifs"],
        "selectPackage":["select the package","sélectionnez le paquet"]
    },
    "showFacteurModal":{
        "date": ["Purchase date","Date d'achat"],
        "waitMoney": ["Not received money e-transfer","Pas reçu de transfert d'argent"],
        "alreadyPaid": ["Already paid?","Déjà payé?"],
        "readMore": ["Read more...","Lire la suite..."],
        "contact": ["contact us!","contactez-nous!"],
        "howTo": ["How to pay?","Comment payer?"],
        "moneyReceivedDate": ["Money received date","Date de réception de l'argent"],
        "sendDate": ["Send date","Envoyer la date"],
        "facteurNotSent": ["Your purchase is not sent yet!","Votre achat n'est pas encore envoyé!"],
        "notReceivedMsg": ["Not received yet?","Pas encore reçu?"]
    },
    "contactUs":{
        "contact": ["contact us!","contactez-nous!"],
        "phone":["Phone number","Numéro de téléphone"], 
        "name":["Name","Nom"], 
        "email":["Email","Email"], 
        "send":["Send","Envoyer"],
        "msgTxt":["Message","Message"],
        "NameRequire":["Name, is required", "Nom, est requis"],
        "msgTxtRequire":["Message, is required", "Message, est requis"],
        "phoneRequire":["Phone number or Email, is required", "Numéro de téléphone ou Email, est requis"],
        "msgSuccess":["The message received, we'll contact you soon.","Le message reçu, nous vous contacterons bientôt."]
    }
}